-- -------------------------------------------------------------
-- TablePlus 6.7.1(636)
--
-- https://tableplus.com/
--
-- Database: BookData.sqlite
-- Generation Time: 2025-09-29 19:57:06.6880
-- -------------------------------------------------------------


CREATE TABLE ZARTICLE ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZRAWINDEX INTEGER, ZRAWISUNREAD INTEGER, Z2RAWARTICLES INTEGER );

CREATE TABLE ZBOOK ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZISHIDDENBYUSER INTEGER, ZRAWAUTOSHELVE INTEGER, ZRAWBOOKSTATE INTEGER, ZRAWBOOKTYPE INTEGER, ZRAWBOOKUPGRADESNEEDED INTEGER, ZRAWCURRENTPOSITION INTEGER, ZRAWERL INTEGER, ZRAWFILESIZE INTEGER, ZRAWHASCOMPANION INTEGER, ZRAWHASFIXEDMOPHIGHLIGHTS INTEGER, ZRAWINBOOKCOVERCHECKED INTEGER, ZRAWISARCHIVABLE INTEGER, ZRAWISDICTIONARY INTEGER, ZRAWISENCRYPTED INTEGER, ZRAWISHIDDEN INTEGER, ZRAWISKEPT INTEGER, ZRAWISMULTIMEDIA INTEGER, ZRAWISPENDINGVERIFICATION INTEGER, ZRAWISSMDCREATEDDICTIONARY INTEGER, ZRAWISTRANSLATIONDICTIONARY INTEGER, ZRAWISUNREAD INTEGER, ZRAWLASTACCESSTIME INTEGER, ZRAWLASTOPENSUCCEEDED INTEGER, ZRAWLASTVIEW INTEGER, ZRAWMAXLOCATION INTEGER, ZRAWMAXPOSITION INTEGER, ZRAWNCXINFOSTORED INTEGER, ZRAWPROGRESSDOTCATEGORY INTEGER, ZRAWPUBLICATIONDATE INTEGER, ZRAWREADSTATE INTEGER, ZRAWREADSTATEORIGIN INTEGER, ZRAWREADINGMODE INTEGER, ZRAWUSERVISIBLELABELING INTEGER, ZCOMPANION INTEGER, ZRAWTIMEDURATIONRESTRICTIONENDDATE TIMESTAMP, ZALTERNATESORTTITLE VARCHAR, ZBOOKID VARCHAR, ZBUNDLEPATH VARCHAR, ZCONTENTTAGS VARCHAR, ZDICTIONARYLOCALEID VARCHAR, ZDICTIONARYSHORTTITLE VARCHAR, ZDICTIONARYSOURCELANG VARCHAR, ZDISPLAYTITLE VARCHAR, ZGROUPID VARCHAR, ZLANGUAGE VARCHAR, ZLONGCURRENTPOSITION VARCHAR, ZLONGMAXPOSITION VARCHAR, ZMANIFESTGUID VARCHAR, ZMIMETYPE VARCHAR, ZPARENTASIN VARCHAR, ZPATH VARCHAR, ZPERASINGUID VARCHAR, ZRAWADS VARCHAR, ZRAWPUBLISHER VARCHAR, ZSHELF VARCHAR, ZSORTTITLE VARCHAR, ZWATERMARK VARCHAR, ZALTERNATESORTAUTHOR BLOB, ZDISPLAYAUTHOR BLOB, ZEXTENDEDMETADATA BLOB, ZORIGINS BLOB, ZSORTAUTHOR BLOB, ZSYNCMETADATAATTRIBUTES BLOB, ZRAWTITLEDETAILSJSON BLOB );

CREATE TABLE ZBOOKEXT ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZBOOKID VARCHAR, ZDOWNLOADORIGIN VARCHAR );

CREATE TABLE ZBOOKUPDATE ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZPLUGINRETRIES INTEGER, ZRAWUPDATESTATE INTEGER, ZENDTIME TIMESTAMP, ZLASTUPDATEATTEMPT TIMESTAMP, ZSTARTTIME TIMESTAMP, ZBOOKID VARCHAR, ZUPDATEID VARCHAR, ZUPDATEREQUESTID VARCHAR );

CREATE TABLE ZCOLLECTIONITEM ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZSYNCHINT INTEGER, ZBOOK INTEGER, ZCOLLECTION INTEGER, ZRAWORDER FLOAT, ZCOLLECTIONID VARCHAR, ZITEMID VARCHAR );

CREATE TABLE ZCOLLECTIONV2 ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZRAWLASTACCESSTIME INTEGER, ZSYNCHINT INTEGER, ZALTERNATESORTNAME VARCHAR, ZCOLLECTIONID VARCHAR, ZCONTENTTYPE VARCHAR, ZLANGUAGE VARCHAR, ZNAME VARCHAR, ZPHONETICNAME VARCHAR, ZSORTNAME VARCHAR );

CREATE TABLE ZGROUP ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZLASTACCESSTIME INTEGER, ZLASTACCESSTIMEFORDOWNLOAD INTEGER, ZRAWPUBLICATIONDATE INTEGER, ZTOTALSIZE INTEGER, ZSERIESCOVERIMAGE INTEGER, ZGROUPID VARCHAR, ZALTERNATESORTAUTHOR VARCHAR, ZALTERNATESORTTITLE VARCHAR, ZCOLLECTIONORDERTYPE VARCHAR, ZCOVERBOOKID VARCHAR, ZDETAILPAGEASIN VARCHAR, ZDISPLAYAUTHOR VARCHAR, ZDISPLAYNAME VARCHAR, ZSERIESTYPE VARCHAR, ZSORTAUTHOR VARCHAR, ZSORTTITLE VARCHAR, ZRAWSERIESCOLLECTIONTYPES BLOB );

CREATE TABLE ZGROUPITEM ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZBOOK INTEGER, ZPARENTCONTAINER INTEGER, Z7_PARENTCONTAINER INTEGER, ZPOSITION INTEGER, ZITEMID VARCHAR, ZPOSITIONLABEL VARCHAR, ZRAWITEMCOLLECTIONTYPE VARCHAR );

CREATE TABLE ZSERIESAUTHOR ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZSERIES INTEGER, Z_FOK_SERIES INTEGER, ZAUTHORNAME VARCHAR, ZAUTHORPRONUNCIATION VARCHAR );

CREATE TABLE ZSERIESIMAGE ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZSERIES INTEGER, ZEXTENSION VARCHAR, ZIMAGEID VARCHAR );

CREATE TABLE Z_PRIMARYKEY (Z_ENT INTEGER PRIMARY KEY, Z_NAME VARCHAR, Z_SUPER INTEGER, Z_MAX INTEGER);

CREATE TABLE Z_METADATA (Z_VERSION INTEGER PRIMARY KEY, Z_UUID VARCHAR(255), Z_PLIST BLOB);

CREATE TABLE Z_MODELCACHE (Z_CONTENT BLOB);

